# Generated by Django 6.0.7 on 2026-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reimbursements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursementpackage",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
