# Generated by Django 6.0.7 on 2026-07-26 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reimbursements", "0004_reimbursementpackage_paid_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursementpackage",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reimbursements_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
