# Generated by Django 6.0.7 on 2026-07-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reimbursements", "0005_add_recipient_to_package"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reimbursementpackage",
            name="description",
        ),
        migrations.AlterField(
            model_name="reimbursementpackage",
            name="status",
            field=models.CharField(
                choices=[("open", "Open for Payment"), ("paid", "Fully Paid")],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
