# Generated by Django 6.0.7 on 2026-07-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reimbursements", "0006_remove_description_from_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursementpackage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
