# Generated by Django 6.0.7 on 2026-07-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reimbursements", "0007_add_deleted_at_to_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagepayment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
