# Generated by Django 6.0.7 on 2026-07-28 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0035_alter_historicalrecord_currency_and_more"),
        ("reimbursements", "0010_add_payer_currency_to_packagepayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reimbursementpackage",
            index=models.Index(
                fields=["status", "expires_at"], name="reimburseme_status_e8aacd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reimbursementpackage",
            index=models.Index(
                fields=["creator", "deleted_at"], name="reimburseme_creator_747ce0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reimbursementpackage",
            index=models.Index(
                fields=["recipient", "deleted_at"],
                name="reimburseme_recipie_73763b_idx",
            ),
        ),
    ]
