# Generated by Django 6.0.7 on 2026-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reimbursements",
            "0011_reimbursementpackage_reimburseme_status_e8aacd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeaccount",
            name="charges_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stripeaccount",
            name="payouts_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
