# Generated by Django 6.0.7 on 2026-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reimbursements", "0012_add_stripe_account_charge_payout_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedStripeEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
