# Generated by Django 6.0.7 on 2026-08-09 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reimbursements", "0013_processedstripeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursementpackage",
            name="recipient_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="reimbursementpackage",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Awaiting Payer"),
                    ("open", "Open for Payment"),
                    ("paid", "Fully Paid"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PackageEmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code_hash", models.CharField(max_length=64)),
                ("salt", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification",
                        to="reimbursements.reimbursementpackage",
                    ),
                ),
            ],
        ),
    ]
