# Generated by Django 6.0.7 on 2026-09-28 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reimbursements", "0016_packagepayment_expected_amount_cents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packageemailverification",
            name="salt",
        ),
    ]
