# Generated by Django 6.0.7 on 2026-07-31 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("djstripe", "0003_2_11"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="The user's Stripe Customer object, if it exists",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.customer",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The user's Stripe Subscription object, if it exists",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.subscription",
            ),
        ),
    ]
