# Generated by Django 6.0.7 on 2026-08-03 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_customuser_subscription"),
        ("djstripe", "0003_2_11"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The user's Stripe Subscription object, if it exists",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="djstripe.subscription",
            ),
        ),
    ]
