# Generated by Django 6.0.7 on 2026-08-06 03:10

from django.db import migrations, models


def backfill_storage_used_bytes(apps, schema_editor):
    """Seed counters from the source of truth: active documents."""
    CustomUser = apps.get_model("billing", "CustomUser")
    DocumentData = apps.get_model("documents", "DocumentData")

    totals = (
        DocumentData.objects.filter(is_active=True)
        .values("user_id")
        .annotate(total=models.Sum("file_size"))
    )
    for row in totals:
        CustomUser.objects.filter(pk=row["user_id"]).update(storage_used_bytes=row["total"] or 0)


def noop(apps, schema_editor):
    """Backfill is intentionally not reversed (counter is derived data)."""


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_unlink_stale_subscriber_customers"),
        ("documents", "0031_remove_duplicate_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="storage_used_bytes",
            field=models.BigIntegerField(
                default=0,
                help_text="Denormalized count of stored document bytes (active documents only), kept in sync by the documents storage signals so quota checks are O(1).",
            ),
        ),
        migrations.RunPython(backfill_storage_used_bytes, noop),
    ]
