# Generated by Django 6.0.8 on 2026-10-07 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_customuser_storage_used_bytes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="subscription",
        ),
    ]
