# Generated by Django 6.0.8 on 2026-10-09 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    ScanUsage = apps.get_model("billing", "ScanUsage")
    MonthlyUsage = apps.get_model("billing", "MonthlyUsage")
    for row in ScanUsage.objects.all():
        MonthlyUsage.objects.create(
            user_id=row.user_id, period=row.period, action="scan", count=row.count
        )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_drop_user_subscription_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(help_text="Calendar month, e.g. 2026-08", max_length=7),
                ),
                ("action", models.CharField(max_length=16)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="scanusage",
            name="unique_scan_usage_period",
        ),
        migrations.AddField(
            model_name="monthlyusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_usage",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="scanusage",
            name="user",
        ),
        migrations.AddConstraint(
            model_name="monthlyusage",
            constraint=models.UniqueConstraint(
                fields=("user", "period", "action"), name="unique_monthly_usage"
            ),
        ),
        migrations.DeleteModel(
            name="ScanUsage",
        ),
    ]
