# Generated by Django 6.0.8 on 2026-10-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0009_monthly_usage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="storage_used_bytes",
        ),
        migrations.AlterField(
            model_name="monthlyusage",
            name="action",
            field=models.CharField(
                help_text="The type of action being tracked. E.g. 'scan' or 'upload'.",
                max_length=16,
            ),
        ),
    ]
