# Generated by Django 6.0.8 on 2026-10-09 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_drop_storage_counter"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MonthlyUsage",
            new_name="MonthlyUploadUsage",
        ),
    ]
