# Generated by Django 6.0.7 on 2026-07-24 23:38

import fernet_fields.fields
import plaid_integration.models
from django.db import migrations, models


class RunSQLPostgresOnly(migrations.RunSQL):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0007_encrypt_existing_plaid_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plaiditem",
            name="access_token",
            field=fernet_fields.fields.EncryptedCharField(max_length=512),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                RunSQLPostgresOnly(
                    sql="ALTER TABLE plaid_integration_plaiditem ALTER COLUMN accounts_data TYPE bytea USING accounts_data::text::bytea",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="plaiditem",
                    name="accounts_data",
                    field=plaid_integration.models.EncryptedJSONField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="plaiditem",
            name="next_cursor",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
