# Generated by Django 6.0.7 on 2026-08-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0008_alter_plaiditem_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaiditem",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
