# Generated by Django 6.0.7 on 2026-08-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plaid_integration", "0009_plaiditem_last_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plaiditem",
            name="institution_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="plaiditem",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="plaiditem",
            name="last_error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="plaiditem",
            name="next_cursor",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
    ]
