# Generated by Django 6.0.7 on 2026-07-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_usersettings_auto_delete_deleted_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
