# Generated by Django 6.0.7 on 2026-08-06 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_backfill_usersettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="auto_delete_deleted_documents",
        ),
    ]
