# Generated by Django 6.0.7 on 2026-08-13 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_usersettings_auto_delete_deleted_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-sent_at"],
                name="idx_notif_recipient_read_sent",
            ),
        ),
    ]
