# Generated by Django 6.0.6 on 2026-07-14 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0020_alter_documentdata_status"),
        ("records", "0015_record_idx_record_list_cover_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentdata",
            index=models.Index(
                fields=["user", "-date_added"], name="idx_doc_list_cover"
            ),
        ),
        migrations.AddIndex(
            model_name="documentdata",
            index=models.Index(
                fields=["user", "did_ocr", "-date_added"], name="idx_doc_main_cover"
            ),
        ),
    ]
