# Generated by Django 6.0.7 on 2026-07-16 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0022_alter_documentdata_options_and_more"),
        ("records", "0017_record_idx_record_expiry_active_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentdata",
            index=models.Index(
                fields=["associated_record", "date_added"],
                name="idx_doc_orphaned_cleanup",
            ),
        ),
        migrations.AddIndex(
            model_name="documentdata",
            index=models.Index(
                fields=["status", "date_added", "filepath"],
                name="idx_doc_reconcile_pending",
            ),
        ),
        migrations.AddIndex(
            model_name="documentdata",
            index=models.Index(
                fields=["status", "date_added"], name="idx_doc_reconcile_error"
            ),
        ),
    ]
