# Generated by Django 6.0.7 on 2026-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0031_remove_duplicate_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdata",
            name="ocr_raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldocumentdata",
            name="ocr_raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
