# Generated by Django 6.0.7 on 2026-08-06 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0032_documentdata_ocr_raw_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentdata",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="documentdata",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="historicaldocumentdata",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="historicaldocumentdata",
            name="is_active",
        ),
    ]
