# Generated by Django 6.0.7 on 2026-08-07 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0033_remove_documentdata_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentdata",
            name="ocr_retries",
        ),
        migrations.RemoveField(
            model_name="historicaldocumentdata",
            name="ocr_retries",
        ),
    ]
