# Generated by Django 6.0.7 on 2026-09-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0034_remove_documentdata_ocr_retries_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentdata",
            name="ocr_metadata",
        ),
        migrations.RemoveField(
            model_name="historicaldocumentdata",
            name="ocr_metadata",
        ),
    ]
