# Generated by Django 6.0.6 on 2026-07-13 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0013_alter_record_record_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["user", "is_active"], name="records_rec_user_id_4d2ecf_idx"),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["user", "-last_edited"], name="records_rec_user_id_916bac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["user", "record_type"], name="records_rec_user_id_20dcdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["expiry_date"], name="records_rec_expiry__a15941_idx"),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["transaction_date"], name="records_rec_transac_d49e5c_idx"),
        ),
    ]
