# Generated by Django 6.0.6 on 2026-07-15 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0015_record_idx_record_list_cover_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["-last_edited"]},
        ),
        migrations.RemoveIndex(
            model_name="record",
            name="records_rec_expiry__a15941_idx",
        ),
        migrations.RenameIndex(
            model_name="record",
            new_name="idx_record_user_active",
            old_name="records_rec_user_id_4d2ecf_idx",
        ),
        migrations.RenameIndex(
            model_name="record",
            new_name="idx_record_user_edited",
            old_name="records_rec_user_id_916bac_idx",
        ),
        migrations.RenameIndex(
            model_name="record",
            new_name="idx_record_user_type",
            old_name="records_rec_user_id_20dcdf_idx",
        ),
        migrations.RenameIndex(
            model_name="record",
            new_name="idx_record_trans_date",
            old_name="records_rec_transac_d49e5c_idx",
        ),
        migrations.AlterField(
            model_name="record",
            name="balance",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="date_added",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="expiry_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="record",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="last_edited",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="merchant",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="record",
            name="products",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("expense_receipt", "Expense Receipt"),
                    ("voucher", "Voucher"),
                    ("warranty_certificate", "Warranty Certificate"),
                    ("vendor_invoice", "Vendor Invoice"),
                    ("customer_invoice", "Customer Invoice"),
                    ("loan_document", "Loan Document"),
                    ("credit_card_statement", "Credit Card Statement"),
                    ("bank_statement", "Bank Statement"),
                    ("purchase_order", "Purchase Order"),
                    ("payslip", "Payslip"),
                    ("tax_document", "Tax Document"),
                    ("service_contract", "Service Contract"),
                    ("lease_agreement", "Lease Agreement"),
                    ("insurance_policy", "Insurance Policy"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="expense_receipt",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="transaction_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["expiry_date", "is_active"], name="idx_record_expiry_active"
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(
                fields=["user", "balance"], name="idx_record_user_balance"
            ),
        ),
    ]
