# Generated by Django 6.0.7 on 2026-07-21 08:32

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plaid_integration",
            "0006_rename_account_name_plaiditem_institution_name_and_more",
        ),
        ("records", "0027_record_fields_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRecord",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "date_added",
                    models.DateField(blank=True, db_index=True, editable=False),
                ),
                (
                    "last_edited",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                ("merchant", models.CharField(default="", max_length=255)),
                (
                    "balance",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                ("products", models.TextField(blank=True, default="")),
                ("transaction_date", models.DateField(db_index=True)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("payment_method_locked", models.BooleanField(default=False)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("expense_receipt", "Expense Receipt"),
                            ("voucher", "Voucher"),
                            ("financial_document", "Financial Document"),
                            ("warranty_certificate", "Warranty Certificate"),
                            ("vendor_invoice", "Vendor Invoice"),
                            ("customer_invoice", "Customer Invoice"),
                            ("loan_document", "Loan Document"),
                            ("credit_card_statement", "Credit Card Statement"),
                            ("bank_statement", "Bank Statement"),
                            ("purchase_order", "Purchase Order"),
                            ("payslip", "Payslip"),
                            ("tax_document", "Tax Document"),
                            ("service_contract", "Service Contract"),
                            ("lease_agreement", "Lease Agreement"),
                            ("insurance_policy", "Insurance Policy"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="expense_receipt",
                        max_length=30,
                    ),
                ),
                (
                    "expiry_notification_sent",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "plaid_transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="records.folder",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plaid_item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="plaid_integration.plaiditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical record",
                "verbose_name_plural": "historical records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
