# Generated by Django 6.0.7 on 2026-07-22 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0029_add_nickname_remove_payment_method_locked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mergelog",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("merge", "Merge"),
                            ("undo_merge", "Undo Merge"),
                            ("detach_receipt", "Detach Receipt"),
                            ("replace_receipt", "Replace Receipt"),
                            ("create_record", "Create Record"),
                            ("update_record", "Update Record"),
                            ("soft_delete", "Soft Delete"),
                            ("hard_delete", "Hard Delete"),
                            ("archive", "Archive"),
                            ("unarchive", "Unarchive"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "merge_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="records.mergelog",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="records.record",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "action"], name="idx_auditlog_user_action"),
                    models.Index(fields=["record", "action"], name="idx_auditlog_record_action"),
                ],
            },
        ),
    ]
