# Generated by Django 6.0.7 on 2026-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0032_add_record_search_trigram_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecord",
            name="reimbursed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="reimbursed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
