# Generated by Django 6.0.7 on 2026-08-08 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0035_alter_historicalrecord_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("merge", "Merge"),
                    ("undo_merge", "Undo Merge"),
                    ("detach_receipt", "Detach Receipt"),
                    ("replace_receipt", "Replace Receipt"),
                    ("create_record", "Create Record"),
                    ("update_record", "Update Record"),
                    ("soft_delete", "Soft Delete"),
                    ("hard_delete", "Hard Delete"),
                    ("archive", "Archive"),
                    ("unarchive", "Unarchive"),
                    ("share", "Share"),
                    ("revoke_share", "Revoke Share"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="RecordShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="records.record",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who granted the share",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["record"], name="idx_recordshare_record"),
                    models.Index(fields=["user"], name="idx_recordshare_user"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record", "user"),
                        name="unique_record_share",
                        violation_error_message="This record is already shared with that user.",
                    )
                ],
            },
        ),
    ]
