# Generated by Django 6.0.7 on 2026-08-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0036_alter_auditlog_action_recordshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordshare",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Access is automatically removed after this time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recordshare",
            name="include_documents",
            field=models.BooleanField(
                default=True,
                help_text="Recipient may also view documents attached to the record.",
            ),
        ),
        migrations.AddField(
            model_name="recordshare",
            name="permission",
            field=models.CharField(
                choices=[("edit", "View and edit"), ("view", "View only")],
                default="edit",
                help_text="Edit grants the recipient the full view+edit experience.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recordshare",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[("reimbursement", "Reimbursement")],
                default="",
                help_text="Optional reason for the grant (shown in audit trails).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="recordshare",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Access was explicitly revoked at this time (audit keeps the row).",
                null=True,
            ),
        ),
    ]
